---
name: "Creates a Named Pipe"
description: "Creates a Named Pipe for integration tests on Windows"
runs:
  using: "composite"
  steps:
    - run: |
        docker pull ${{ env.NPIPE_IMAGE }}
        docker create --name npipe ${{ env.NPIPE_IMAGE }}
        docker cp npipe:/npipe.exe ./npipe.exe
        docker rm npipe
        docker rmi ${{ env.NPIPE_IMAGE }}
        ./npipe.exe \\\\.\\pipe\\hijack_test &
        disown -h
      shell: bash
      env:
        NPIPE_IMAGE: gesellix/npipe:2023-07-02T11-38-00
branding:
  icon: "tag"
  color: "blue"
...
