---
name: "Install Docker on macOS"
description: "Performs an unattended install of a Docker runtime for MacOS"
# Colima should be pre-installed: https://github.com/actions/runner-images/pull/6285
runs:
  using: "composite"
  steps:
    - run: brew install docker colima
      shell: bash
    - run: colima start
      shell: bash
branding:
  icon: "tag"
  color: "blue"
...
